#JSDoc generation workflow for CI/CD pipeline
name: JSDoc generation workflow 
on: 
  push:
    paths: 
    - 'source/**'
    branches:
    - '**-release'
jobs:
  create-docs: # Create JSDocs from source folder 
    name: Create JSDocs
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Generate JSDocs
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./source
          recurse: true
          output_dir: ./docs

      - name: Push JSDocs
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: '${GITHUB_REF##*/}' 
