# Release Code workflow for CI/CD pipeline
name: Release code workflow
on: 
  pull_request: 
    paths: 
    - 'source/**'
    branches:
    - 'staging'
jobs: 
  codacy-scan: #Run codacy code quality scan
    name: Codacy Analysis CLI Scan
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with: 
          directory: /home/runner/work/cse110-sp21-group9/cse110-sp21-group9/source/
  unit-test: #Run automated developer unit tests
    name: Automated developer unit tests
    needs: codacy-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: npm install, and test
        run: |
          npm install
          npm test -- dev
        env:
          CI: true
    

  


    