#JSDoc generation workflow for CI/CD pipeline
name: JSDoc generation workflow 
on: 
  push:
    paths: 
    - 'source/**'
    branches:
    - 'staging'
jobs:
  unit-test: #Run automated developer + tester unit tests
    name: Automated developer + tester unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: npm install, and test
        run: |
          npm install
          npm test
        env:
          CI: true
  create-docs: # Create JSDocs from source folder 
    name: Create JSDocs
    needs: unit-test
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
        
      - name: Generate JSDocs
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./source
          recurse: true
          output_dir: ./docs

      - name: Push JSDocs
        uses: stefanzweifel/git-auto-commit-action@v4
        with: 
          commit_message: (Automated) Push JSDocs 
