name: Test workflow for CI/CD pipeline
on: 
  push: 
    paths: 
    - 'source/**'
jobs: 
  codacy-scan: 
    name: Codacy Analysis CLI
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with: 
          directory: ./source
    

  


    